# Generated by Django 5.0.6 on 2024-07-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_person_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='color',
        ),
        migrations.AddField(
            model_name='person',
            name='course',
            field=models.CharField(default='CSE', max_length=100),
        ),
    ]
